#!/usr/bin/env bash

VERSION="1.9.4"

function die() {
    echo "$1"
    [[ -z "$2" ]] || exit $2
    exit 1
}

packages="subversion
cmake
yasm
build-essential
autoconf
libtool
zlib1g-dev
libbz2-dev
libxml2-dev
libogg-dev
libtheora-dev
libvorbis-dev
libsamplerate-dev
libfribidi-dev
libfreetype6-dev
libfontconfig1-dev
libass-dev
libmp3lame-dev
libx264-dev
libjansson-dev
intltool
libglib2.0-dev
libdbus-glib-1-dev
libgtk-3-dev
libgudev-1.0-dev
libwebkitgtk-3.0-dev
libnotify-dev
libgstreamer1.0-dev
libgstreamer-plugins-base1.0-dev
libappindicator-dev"

install_packages=""
for package in $packages; do
    dpkg -s "$package" >/dev/null 2>&1 || install_packages="$install_packages $package"
done
[[ $install_packages == "" ]] || sudo apt-get install $install_packages -y

svn co svn://svn.handbrake.fr/HandBrake/trunk hb-trunk
cd hb-trunk
[[ -d build ]] && rm -rf build
./configure --launch || die "Configure failed"

