#!/usr/bin/env bash

VERSION="1.9.4"

function die() {
    echo "$1"
    [[ -z "$2" ]] || exit $2
    exit 1
}

packages="subversion
yasm
build-essential
autoconf
libtool
zlib1g-dev
libbz2-dev
libxml2-dev
libogg-dev
libtheora-dev
libvorbis-dev
libsamplerate-dev
libfribidi-dev
libfreetype6-dev
libfontconfig1-dev
libass-dev
intltool
libglib2.0-dev
libdbus-glib-1-dev
libgtk2.0-dev
libgudev-1.0-dev
libwebkit-dev
libnotify-dev
libgstreamer0.10-dev
libgstreamer-plugins-base0.10-dev
libappindicator-dev"

install_packages=""
for package in $packages; do
    dpkg -s "$package" >/dev/null 2>&1 || install_packages="$install_packages $package"
done
[[ $install_packages == "" ]] || sudo apt-get install $install_packages -y

svn co svn://svn.handbrake.fr/HandBrake/trunk hb-trunk
cd hb-trunk
./configure --launch || die "Configure failed"

