#!/usr/bin/env bash

VERSION=3.9.1 # default version
[[ -z "$1" ]] || VERSION="$1"

function die() {
    # $1 - the exit code
    # $2 $... - the message string

    retcode=$1
    (( $retcode == 0 )) || echo -en "\E[31mERROR: "
    echo "$2"
    (( $retcode == 0 )) || echo -en "\E[0m"
    exit $retcode
}

dpkg -s "maven" >/dev/null 2>&1 && {
    echo "removing maven..."
    sudo apt remove --purge maven -y || die -1 "uninstall of maven failed"
}

[[ "`mvn --version |head -1 |cut -f2 -d' '`" == "${VERSION}" ]] || {
    echo "downloading and installing maven ${VERSION}..."
    wget https://apache.org/dist/maven/maven-3/${VERSION}/binaries/apache-maven-${VERSION}-bin.tar.gz -O /tmp/apache-maven-${VERSION}-bin.tar.gz || die -1 "maven download failed"
    sudo tar xf /tmp/apache-maven-*.tar.gz -C /opt
    sudo ln -s /opt/apache-maven-${VERSION} /opt/maven
    [[ -f /etc/profile.d/maven.sh ]] || {
        sudo bash -c 'cat << EOF > /etc/profile.d/maven.sh
export JAVA_HOME=/usr/lib/jvm/default-java
export M2_HOME=/opt/maven
export MAVEN_HOME=/opt/maven
export PATH=/opt/maven/bin:$PATH
EOF'
        sudo chown root:root /etc/profile.d/maven.sh
        sudo chmod +x /etc/profile.d/maven.sh
        source /etc/profile.d/maven.sh
    }
}
