#!/usr/bin/env bash

VERSION="20" # default version
[[ -z "$1" ]] || VERSION="$1"

[[ $VERSION == "17" ]] && {
    JAVA_VERSION="17.0.2"
    JAVA_ID="dfd4a8d0985749f896bed50d7138ee7f/8"
}

[[ $VERSION == "19" ]] && {
    JAVA_VERSION="19.0.2"
    JAVA_ID="fdb695a9d9064ad6b064dc6df578380c/7"
}

[[ $VERSION == "20" ]] && {
    JAVA_VERSION="20.0.1"
    JAVA_ID="b4887098932d415489976708ad6d1a4b/9"
}

function die() {
    # $1 - the exit code
    # $2 $... - the message string

    retcode=$1
    (( $retcode == 0 )) || echo -en "\E[31mERROR: "
    echo "$2"
    (( $retcode == 0 )) || echo -en "\E[0m"
    exit $retcode
}

dpkg -s "default-jdk" >/dev/null 2>&1 || {
    echo "installing default-jdk..."
    sudo apt install default-jdk -y || die -1 "package installation failed"
}

[[ "`java --version |head -1 |cut -f2 -d' '`" == "${JAVA_VERSION}" ]] || {
    echo "downloading and installing openjdk ${JAVA_VERSION}..."
    cd /tmp
    wget https://download.java.net/java/GA/jdk${JAVA_VERSION}/$JAVA_ID/GPL/openjdk-${JAVA_VERSION}_linux-x64_bin.tar.gz -O /tmp/openjdk-${JAVA_VERSION}-linux-x64_bin.tar.gz || die -1 "openjdk download failed"
    sudo tar xfvz /tmp/openjdk-${JAVA_VERSION}-linux-x64_bin.tar.gz --directory /usr/lib/jvm || die -1 "failed extracting openjdk-${JAVA_VERSION}"
    rm -f /tmp/openjdk-${JAVA_VERSION}-linux-x64_bin.tar.gz
    for file in /usr/lib/jvm/jdk-${JAVA_VERSION}/bin/*
    do 
        sudo update-alternatives --install /usr/bin/$(basename $file) $(basename $file) $file 100 || die -1 "failed update-alternatives --install on $file"
        sudo update-alternatives --set $(basename $file) $file || die -1 "failed update alternatives --set on $file"
    done
}
