#!/usr/bin/env bash

# Script to install Hadoop per this tutorial:
#   http://www.michael-noll.com/tutorials/running-hadoop-on-ubuntu-linux-single-node-cluster/
#
# ccarey - 2013-04-21

die() {
    # $1 - the exit code
    # $2 $... - the message string

    retcode=$1
    shift
    printf >&2 "%s\n" "$@"
    exit $retcode
}

HADOOP_MIRROR="http://mirror.cogentco.com/pub/apache/hadoop/common/"
HADOOP_VERSION="2.5.0"
ORIG_DIR="`pwd`"
INSTALL_ROOT="/opt"

# Pre-requisites

# Check for java... install if not there

type java >/dev/null 2>&1 || sudo apt-get -y install openjdk-7-jdk

# Add dedicated Hadoop system user

sudo addgroup hadoop
sudo adduser --ingroup hadoop hduser

# Configure SSH

echo -n "hduser "
su - hduser -c "ssh-keygen -t rsa -P '' && cat .ssh/id_rsa.pub >> .ssh/authorized_keys && ssh -o StrictHostKeyChecking=no localhost 'exit'" || die 1 "cannot continue from configure of SSH"

# Get Hadoop

cd /tmp

[[ -d hadoop-${HADOOP_VERSION} ]] || {
    [[ -f hadoop-${HADOOP_VERSION}.tar.gz ]] || {
        wget ${HADOOP_MIRROR}/hadoop-${HADOOP_VERSION}/hadoop-${HADOOP_VERSION}.tar.gz || die 1 "download of hadoop failed ... cannot continue"
    }
}

# Extract/Install Hadoop

cd ${INSTALL_ROOT}
sudo tar xfz /tmp/hadoop-${HADOOP_VERSION}.tar.gz
sudo chown -R hduser:hadoop hadoop-${HADOOP_VERSION}
sudo ln -s hadoop-${HADOOP_VERSION} hadoop

# Update $HOME/.bashrc

sudo chmod 666 /home/hduser/.bashrc
cat << EOF >> /home/hduser/.bashrc
# Set Hadoop-related environment variables
export HADOOP_HOME=${INSTALL_ROOT}/hadoop

# Set JAVA_HOME (we will also configure JAVA_HOME directly for Hadoop later on)
export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64

# Some convenient aliases and functions for running Hadoop-related commands
unalias hdpfs &> /dev/null
alias hdpfs="hadoop fs"
unalias hdpls &> /dev/null
alias hdpls="fs -ls"

# If you have LZO compression enabled in your Hadoop cluster and
# compress job outputs with LZOP (not covered in this tutorial):
# Conveniently inspect an LZOP compressed file from the command
# line; run via:
#
# $ lzohead /hdfs/path/to/lzop/compressed/file.lzo
#
# Requires installed 'lzop' command.
#
lzohead () {
    hadoop fs -cat $1 | lzop -dc | head -1000 | less
}

# Add Hadoop bin/ directory to PATH
export PATH=\$PATH:\$HADOOP_HOME/bin
EOF

sudo chmod 644 /home/hduser/.bashrc

# Configuration

# hadoop-env.sh

sudo chmod 666 ${INSTALL_ROOT}/hadoop/etc/hadoop/hadoop-env.sh
sudo echo "export HADOOP_OPTS=-Djava.net.preferIPv4Stack=true" >> ${INSTALL_ROOT}/hadoop/etc/hadoop/hadoop-env.sh
sudo chmod 664 ${INSTALL_ROOT}/hadoop/etc/hadoop/hadoop-env.sh

# etc/hadoop/*-site.xml

sudo mkdir -p ${INSTALL_ROOT}/hadoop/tmp
sudo chown hduser:hadoop ${INSTALL_ROOT}/hadoop/tmp
sudo chmod 750 ${INSTALL_ROOT}/hadoop/tmp

sudo sed -i "s/<configuration>//g" ${INSTALL_ROOT}/hadoop/etc/hadoop/core-site.xml
sudo sed -i "s/<\/configuration>//g" ${INSTALL_ROOT}/hadoop/etc/hadoop/core-site.xml

sudo chmod 666 ${INSTALL_ROOT}/hadoop/etc/hadoop/core-site.xml
sudo cat << EOF >> ${INSTALL_ROOT}/hadoop/etc/hadoop/core-site.xml
<configuration>
    <property>
        <name>hadoop.tmp.dir</name>
        <value>${INSTALL_ROOT}/hadoop/tmp</value>
        <description>A base for other temporary directories.</description>
    </property>

    <property>
        <name>fs.default.name</name>
        <value>hdfs://localhost:54310</value>
        <description>The name of the default file system.  A URI whose
        scheme and authority determine the FileSystem implementation.  The
        uri's scheme determines the config property (fs.SCHEME.impl) naming
        the FileSystem implementation class.  The uri's authority is used to
        determine the host, port, etc. for a filesystem.</description>
    </property>
</configuration>
EOF
sudo chmod 664 ${INSTALL_ROOT}/hadoop/etc/hadoop/core-site.xml

sudo sed -i "s/<configuration>//g" ${INSTALL_ROOT}/hadoop/etc/hadoop/mapred-site.xml
sudo sed -i "s/<\/configuration>//g" ${INSTALL_ROOT}/hadoop/etc/hadoop/mapred-site.xml

sudo chmod 666 ${INSTALL_ROOT}/hadoop/etc/hadoop/mapred-site.xml
sudo cat << EOF >> ${INSTALL_ROOT}/hadoop/etc/hadoop/mapred-site.xml
<configuration>
    <property>
        <name>mapred.job.tracker</name>
        <value>localhost:54311</value>
        <description>The host and port that the MapReduce job tracker runs
        at.  If "local", then jobs are run in-process as a single map
        and reduce task.
        </description>
    </property>
</configuration>
EOF
sudo chmod 664 ${INSTALL_ROOT}/hadoop/etc/hadoop/mapred-site.xml

sudo sed -i "s/<configuration>//g" ${INSTALL_ROOT}/hadoop/etc/hadoop/hdfs-site.xml
sudo sed -i "s/<\/configuration>//g" ${INSTALL_ROOT}/hadoop/etc/hadoop/hdfs-site.xml

sudo chmod 666 ${INSTALL_ROOT}/hadoop/etc/hadoop/hdfs-site.xml
sudo cat << EOF >> ${INSTALL_ROOT}/hadoop/etc/hadoop/hdfs-site.xml
<configuration>
    <property>
        <name>dfs.replication</name>
        <value>1</value>
        <description>Default block replication.
        The actual number of replications can be specified when the file is created.
        The default is used if replication is not specified in create time.
        </description>
    </property>
</configuration>
EOF
sudo chmod 664 ${INSTALL_ROOT}/hadoop/etc/hadoop/hdfs-site.xml

# Format HDFS filesystem

echo -n "hduser "
su - hduser -c "${INSTALL_ROOT}/hadoop/bin/hadoop namenode -format"
