#!/usr/bin/env bash

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

MUSIC_ROOT="/mnt/morpheus/data/Music/"

PLAYLIST="$1"
FOLDER_SONG="$2"

if [ -d ${MUSIC_ROOT}${FOLDER_SONG} ]
then
    echo "Adding folder ${FOLDER_SONG}..."
    find ${MUSIC_ROOT}${FOLDER_SONG} -name *.mp3 >> ${PLAYLIST}
else
    echo "Adding song ${FOLDER_SONG}..."
    find ${MUSIC_ROOT}${FOLDER_SONG} -print >> ${PLAYLIST}
fi

IFS=${SAVEIFS}

