#!/usr/bin/env bash

DATE=`date +%Y%m%d%H%M%S`
SRC=/mnt/usbdisk1/Music
DEST=/home/ccarey/test-sync

[ -z "$1" ] || {
    [ -d "$1" ] && DEST="$1"
}

echo "$DATE"
echo "$SRC"
echo "$DEST"

for file in `cat $SRC/to-sync`
do
    grep -v "#EXT" "$SRC/$file" >> /tmp/$DATE.m3u
done

sort -u /tmp/$DATE.m3u > /tmp/$DATE && mv /tmp/$DATE /tmp/$DATE.m3u

sed -i -e 's/[*?\[]/\\&/g' -e 's/[*?[]/&/g' -e T -e 's/\\\\/\\/g' /tmp/$DATE.m3u

rsync -vrtD --dry-run --size-only --include-from=/tmp/$DATE.m3u --include='*/' --exclude='*' \
    --delete --delete-excluded --prune-empty-dirs $SRC $DEST

echo "total size of files to copy is above... N to quit"
read resp

[ "$resp" == "N" ] && exit 0

rsync -vrtD --size-only --include-from=/tmp/$DATE.m3u --include='*/' --exclude='*' --delete \
    --delete-excluded --prune-empty-dirs $SRC $DEST

for file in `cat $SRC/to-sync`
do
    cp $SRC/$file $DEST/Music
done

# rm /tmp/$DATE.m3u